# Dependencies
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
syntax_highlighter: coderay

syntax_highlighter_opts:
  line_numbers: ''

defaults:
  - scope:
      path: ""  # All files in the project.
    values:
      layout: "default"

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink: pretty

# Setup
title: Jeremy Fleischman
description: ""
url: https://www.jflei.com
baseurl: ""

author:
  name: 'Jeremy Fleischman'
  url: https://www.jflei.com

paginate: 1
paginate_path: "/blog/page:num"

# Custom vars

date_format: "%B %-d, %Y"
