# Dependencies
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
syntax_highlighter: coderay

syntax_highlighter_opts:
  line_numbers: ''

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink: pretty

# Setup
title: jflei
description: "jfly.com was too expensive"
url: https://www.jflei.com
baseurl: ""

author:
  name: 'Jeremy Fleischman'
  url: https://www.jflei.com

paginate: 5

# Custom vars

date_format: "%B %-d, %Y"
