# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM
  use_coderay: true
  hard_wrap: false
  coderay:
    coderay_line_numbers: ''

# Permalinks
permalink:        pretty

# Setup
title:            jflei
description:      "jfly.com was too expensive"
url:              http://jflei.com
baseurl:          /

author:
  name:           'Jeremy Fleischman'
  url:            http://jflei.com

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde
